START = "<pre>Konnichiwa</pre> <b>{}</b> <pre>san!\nPress</pre> /help <pre>to see more info.</pre>"
HAPPY_FACE = '😄'
COUNTRY_NOT_FOUND = "<pre>Country not found or doesn't have any cases.</pre>"
LEN_ZERO = "<pre>Please enter a country name.\ne.g. /search china</pre>"
COUNTRY_DATA = ("<b>Country :</b> <pre>{}</pre>\n"
                "<b>Country Code :</b> <pre>{}</pre>\n"
                "<b>Cases :</b> <pre>{}</pre>\n"
                "<b>Cases Today :</b> <pre>{}</pre>\n"
                "<b>Deaths :</b> <pre>{}</pre>\n"
                "<b>Deaths Today :</b> <pre>{}</pre>\n"
                "<b>Recovered :</b> <pre>{}</pre>\n"
                "<b>Active :</b> <pre>{}</pre>\n"
                "<b>Critical :</b> <pre>{}</pre>\n"
                "<b>Cases/million :</b> <pre>{}</pre>\n"
                "<b>Deaths/million :</b> <pre>{}</pre>\n"
                "<b>Tests :</b> <pre>{}</pre>\n"
                "<b>Tests/million :</b> <pre>{}</pre>\n")

GLOBAL_DATA = ("<b>Cases :</b> <pre>{}</pre>\n"
                "<b>Cases Today :</b> <pre>{}</pre>\n"
                "<b>Deaths :</b> <pre>{}</pre>\n"
                "<b>Deaths Today :</b> <pre>{}</pre>\n"
                "<b>Recovered :</b> <pre>{}</pre>\n"
                "<b>Active :</b> <pre>{}</pre>\n"
                "<b>Critical :</b> <pre>{}</pre>\n"
                "<b>Cases/million :</b> <pre>{}</pre>\n"
                "<b>Deaths/million :</b> <pre>{}</pre>\n"
                "<b>Tests :</b> <pre>{}</pre>\n"
                "<b>Tests/million :</b> <pre>{}</pre>\n"
                "<b>Affected Countries :</b> <pre>{}</pre>")

COUNTRY_LIST_1 = ('<pre>Afghanistan</pre>\n'
                '<pre>Åland Islands</pre>\n'
                '<pre>Albania</pre>\n'      
                '<pre>Algeria</pre>\n'
                '<pre>American Samoa</pre>\n'
                '<pre>Andorra</pre>\n'
                '<pre>Angola</pre>\n'
                '<pre>Anguilla</pre>\n'
                '<pre>Antarctica</pre>\n'
                '<pre>Antigua & Barbuda</pre>\n'
                '<pre>Argentina</pre>\n'
                '<pre>Armenia</pre>\n'
                '<pre>Aruba</pre>\n'
                '<pre>Australia</pre>\n'
                '<pre>Austria</pre>\n'
                '<pre>Azerbaijan</pre>\n'
                '<pre>Bahamas</pre>\n'
                '<pre>Bahrain</pre>\n'
                '<pre>Bangladesh</pre>\n'
                '<pre>Barbados</pre>\n'
                '<pre>Belarus</pre>\n'
                '<pre>Belgium</pre>\n'
                '<pre>Belize</pre>\n'
                '<pre>Benin</pre>\n'
                '<pre>Bermuda</pre>\n'
                '<pre>Bhutan</pre>\n'
                '<pre>Bolivia</pre>\n'
                '<pre>Bosnia & Herzegovina</pre>\n'
                '<pre>Botswana</pre>\n'
                '<pre>Bouvet Island</pre>\n'
                '<pre>Brazil</pre>\n'
                '<pre>British Indian Ocean Territory</pre>\n'
                '<pre>British Virgin Islands</pre>\n'
                '<pre>Brunei</pre>\n'
                '<pre>Bulgaria</pre>\n'
                '<pre>Burkina Faso</pre>\n'
                '<pre>Burundi</pre>\n'
                '<pre>Cambodia</pre>\n'
                '<pre>Cameroon</pre>\n'
                '<pre>Canada</pre>\n'
                '<pre>Cape Verde</pre>\n'
                '<pre>Caribbean Netherlands</pre>\n'
                '<pre>Cayman Islands</pre>\n'
                '<pre>Central African Republic</pre>\n'
                '<pre>Chad</pre>\n'
                '<pre>Chile</pre>\n'
                '<pre>China</pre>\n'
                '<pre>Christmas Island</pre>\n'
                '<pre>Cocos (Keeling) Islands</pre>\n'
                '<pre>Colombia</pre>\n'
                '<pre>Comoros</pre>\n'
                '<pre>Congo - Brazzaville</pre>\n'
                '<pre>Congo - Kinshasa</pre>\n'
                '<pre>Cook Islands</pre>\n'
                '<pre>Costa Rica</pre>\n'
                '<pre>Côte d’Ivoire</pre>\n'
                '<pre>Croatia</pre>\n'
                '<pre>Cuba</pre>\n'
                '<pre>Curaçao</pre>\n'
                '<pre>Cyprus</pre>\n'
                '<pre>Czechia</pre>\n'
                '<pre>Denmark</pre>\n'
                '<pre>Djibouti</pre>\n'
                '<pre>Dominica</pre>\n'
                '<pre>Dominican Republic</pre>\n'
                '<pre>Ecuador</pre>\n'
                '<pre>Egypt</pre>\n'
                '<pre>El Salvador</pre>\n'
                '<pre>Equatorial Guinea</pre>\n'
                '<pre>Eritrea</pre>\n'
                '<pre>Estonia</pre>\n'
                '<pre>Eswatini</pre>\n'
                '<pre>Ethiopia</pre>\n'
                '<pre>Falkland Islands</pre>\n'
                '<pre>Faroe Islands</pre>\n'
                '<pre>Fiji</pre>\n'
                '<pre>Finland</pre>\n'
                '<pre>France</pre>\n'
                '<pre>French Guiana</pre>\n'
                '<pre>French Polynesia</pre>\n'
                '<pre>French Southern Territories</pre>\n'
                '<pre>Gabon</pre>\n'
                '<pre>Gambia</pre>\n'
                '<pre>Georgia</pre>\n'
                '<pre>Germany</pre>\n'
                '<pre>Ghana</pre>\n'
                '<pre>Gibraltar</pre>\n'
                '<pre>Greece</pre>\n'
                '<pre>Greenland</pre>\n'
                '<pre>Grenada</pre>\n'
                '<pre>Guadeloupe</pre>\n'
                '<pre>Guam</pre>\n'
                '<pre>Guatemala</pre>\n'
                '<pre>Guernsey</pre>\n'
                '<pre>Guinea</pre>\n'
                '<pre>Guinea-Bissau</pre>\n'
                '<pre>Guyana</pre>\n'
                '<pre>Haiti</pre>\n'
                '<pre>Heard & McDonald Islands</pre>\n'
                '<pre>Honduras</pre>\n')
                
COUNTRY_LIST_2 = ('<pre>Hong Kong SAR China</pre>\n'
                '<pre>Hungary</pre>\n'
                '<pre>Iceland</pre>\n'
                '<pre>India</pre>\n'
                '<pre>Indonesia</pre>\n'
                '<pre>Iran</pre>\n'
                '<pre>Iraq</pre>\n'
                '<pre>Ireland</pre>\n'
                '<pre>Isle of Man</pre>\n'
                '<pre>Israel</pre>\n'
                '<pre>Italy</pre>\n'
                '<pre>Jamaica</pre>\n'
                '<pre>Japan</pre>\n'
                '<pre>Jersey</pre>\n'
                '<pre>Jordan</pre>\n'
                '<pre>Kazakhstan</pre>\n'
                '<pre>Kenya</pre>\n'
                '<pre>Kiribati</pre>\n'
                '<pre>Kuwait</pre>\n'
                '<pre>Kyrgyzstan</pre>\n'
                '<pre>Laos</pre>\n'
                '<pre>Latvia</pre>\n'
                '<pre>Lebanon</pre>\n'
                '<pre>Lesotho</pre>\n'
                '<pre>Liberia</pre>\n'
                '<pre>Libya</pre>\n'
                '<pre>Liechtenstein</pre>\n'
                '<pre>Lithuania</pre>\n'
                '<pre>Luxembourg</pre>\n'
                '<pre>Macao SAR China</pre>\n'
                '<pre>Madagascar</pre>\n'
                '<pre>Malawi</pre>\n'
                '<pre>Malaysia</pre>\n'
                '<pre>Maldives</pre>\n'
                '<pre>Mali</pre>\n'
                '<pre>Malta</pre>\n'
                '<pre>Marshall Islands</pre>\n'
                '<pre>Martinique</pre>\n'
                '<pre>Mauritania</pre>\n'
                '<pre>Mauritius</pre>\n'
                '<pre>Mayotte</pre>\n'
                '<pre>Mexico</pre>\n'
                '<pre>Micronesia</pre>\n'
                '<pre>Moldova</pre>\n'
                '<pre>Monaco</pre>\n'
                '<pre>Mongolia</pre>\n'
                '<pre>Montenegro</pre>\n'
                '<pre>Montserrat</pre>\n'
                '<pre>Morocco</pre>\n'
                '<pre>Mozambique</pre>\n'
                '<pre>Myanmar (Burma)</pre>\n'
                '<pre>Namibia</pre>\n'
                '<pre>Nauru</pre>\n'
                '<pre>Nepal</pre>\n'
                '<pre>Netherlands</pre>\n'
                '<pre>New Caledonia</pre>\n'
                '<pre>New Zealand</pre>\n'
                '<pre>Nicaragua</pre>\n'
                '<pre>Niger</pre>\n'
                '<pre>Nigeria</pre>\n'
                '<pre>Niue</pre>\n'
                '<pre>Norfolk Island</pre>\n'
                '<pre>North Korea</pre>\n'
                '<pre>North Macedonia</pre>\n'
                '<pre>Northern Mariana Islands</pre>\n'
                '<pre>Norway</pre>\n'
                '<pre>Oman</pre>\n'
                '<pre>Pakistan</pre>\n'
                '<pre>Palau</pre>\n'
                '<pre>Palestinian Territories</pre>\n'
                '<pre>Panama</pre>\n'
                '<pre>Papua New Guinea</pre>\n'
                '<pre>Paraguay</pre>\n'
                '<pre>Peru</pre>\n'
                '<pre>Philippines</pre>\n'
                '<pre>Pitcairn Islands</pre>\n'
                '<pre>Poland</pre>\n'
                '<pre>Portugal</pre>\n'
                '<pre>Puerto Rico</pre>\n'
                '<pre>Qatar</pre>\n'
                '<pre>Réunion</pre>\n'
                '<pre>Romania</pre>\n'
                '<pre>Russia</pre>\n'
                '<pre>Rwanda</pre>\n'
                '<pre>Samoa</pre>\n'
                '<pre>San Marino</pre>\n'
                '<pre>São Tomé & Príncipe</pre>\n'
                '<pre>Saudi Arabia</pre>\n'
                '<pre>Senegal</pre>\n'
                '<pre>Serbia</pre>\n'
                '<pre>Seychelles</pre>\n'
                '<pre>Sierra Leone</pre>\n'
                '<pre>Singapore</pre>\n'
                '<pre>Sint Maarten</pre>\n'
                '<pre>Slovakia</pre>\n'
                '<pre>Slovenia</pre>\n'
                '<pre>Solomon Islands</pre>\n'
                '<pre>Somalia</pre>\n'
                '<pre>South Africa</pre>\n'
                '<pre>South Georgia & South Sandwich Islands</pre>\n')
                
COUNTRY_LIST_3 = ('<pre>South Korea</pre>\n'
                '<pre>South Sudan</pre>\n'
                '<pre>Spain</pre>\n'
                '<pre>Sri Lanka</pre>\n'
                '<pre>St. Barthélemy</pre>\n'
                '<pre>St. Helena</pre>\n'
                '<pre>St. Kitts & Nevis</pre>\n'
                '<pre>St. Lucia</pre>\n'
                '<pre>St. Martin</pre>\n'
                '<pre>St. Pierre & Miquelon</pre>\n'
                '<pre>St. Vincent & Grenadines</pre>\n'
                '<pre>Sudan</pre>\n'
                '<pre>Suriname</pre>\n'
                '<pre>Svalbard & Jan Mayen</pre>\n'
                '<pre>Sweden</pre>\n'
                '<pre>Switzerland</pre>\n'
                '<pre>Syria</pre>\n'
                '<pre>Taiwan</pre>\n'
                '<pre>Tajikistan</pre>\n'
                '<pre>Tanzania</pre>\n'
                '<pre>Thailand</pre>\n'
                '<pre>Timor-Leste</pre>\n'
                '<pre>Togo</pre>\n'
                '<pre>Tokelau</pre>\n'
                '<pre>Tonga</pre>\n'
                '<pre>Trinidad & Tobago</pre>\n'
                '<pre>Tunisia</pre>\n'
                '<pre>Turkey</pre>\n'
                '<pre>Turkmenistan</pre>\n'
                '<pre>Turks & Caicos Islands</pre>\n'
                '<pre>Tuvalu</pre>\n'
                '<pre>U.S. Outlying Islands</pre>\n'
                '<pre>U.S. Virgin Islands</pre>\n'
                '<pre>Uganda</pre>\n'
                '<pre>Ukraine</pre>\n'
                '<pre>United Arab Emirates</pre>\n'
                '<pre>United Kingdom</pre>\n'
                '<pre>United States</pre>\n'
                '<pre>Uruguay</pre>\n'
                '<pre>Uzbekistan</pre>\n'
                '<pre>Vanuatu</pre>\n'
                '<pre>Vatican City</pre>\n'
                '<pre>Venezuela</pre>\n'
                '<pre>Vietnam</pre>\n'
                '<pre>Wallis & Futuna</pre>\n'
                '<pre>Western Sahara</pre>\n'
                '<pre>Yemen</pre>\n'
                '<pre>Zambia</pre>\n'
                '<pre>Zimbabwe</pre>\n')

HELP = ("<pre>Konnichiwa!</pre> <b>{}</b> <pre>san!\nI'm</pre> <b>Corona Chan.</b>"
        "\n<pre>I'll send you Corona stats whenever you need.</pre>\n"
        "<b>-----------------Commands----------------</b>\n"
        "<pre>/start  -  Wake me up!</pre>\n"
        "<pre>/search [Country Name]  -  Search for a specific country</pre>\n"
        "<pre>/list - shows a list of all the countries.</pre>\n"
        "<pre>/global  -  get the overall corona stats of Earth.</pre>\n"
        "<pre>/help  -  you'll see this.</pre>")
